### ISSUE TITLE
Trigger router 'route' event with `pushState: true`

### ISSUE THREAD

**Issue by adamyonk** [HenrikJoreteg/set-query-string#1]
Is it possible to get the `navigate({ trigger: true })`-like functionality with this? I'm wanting a ampersand-router `route` event to fire when I do something like `setQueryString({ foo: 'bar' }, { pushState: true })`.

**Comment by HenrikJoreteg** [comment]
Hi, @adamyonk, sorry this sat so long. The `route` event is specific to the event model used in ampersand/backbone. If I was to fire such an event directly from this module, I'd have to require the event code, which is bigger than this whole module.

I think in your case, I'd suggest simply calling `.trigger` manually after your code that calls this module: http://ampersandjs.com/docs#ampersand-events-trigger

Hope that helps (though, you've probably come up with something else by now  :smile:).  Cheers!

**Comment by adamyonk** [comment]
I think I did, and it seems like this was a bad idea anyway. :) I appreciate your reply!
